/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinosRouteImport } from './routes/treinos'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PersonaisRouteImport } from './routes/personais'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LojaProRouteImport } from './routes/loja-pro'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as EliteRouteImport } from './routes/elite'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArquivosRouteImport } from './routes/arquivos'
import { Route as AnamneseRouteImport } from './routes/anamnese'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca.index'
import { Route as LojaIdRouteImport } from './routes/loja.$id'
import { Route as LojaProConfigRouteImport } from './routes/loja-pro.config'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as BibliotecaIdRouteImport } from './routes/biblioteca.$id'
import { Route as AlunosIdRouteImport } from './routes/alunos.$id'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'

const TreinosRoute = TreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaisRoute = PersonaisRouteImport.update({
  id: '/personais',
  path: '/personais',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaProRoute = LojaProRouteImport.update({
  id: '/loja-pro',
  path: '/loja-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteRoute = EliteRouteImport.update({
  id: '/elite',
  path: '/elite',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivosRoute = ArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => rootRouteImport,
} as any)
const AnamneseRoute = AnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliotecaRoute,
} as any)
const LojaIdRoute = LojaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LojaRoute,
} as any)
const LojaProConfigRoute = LojaProConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => LojaProRoute,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIdRoute = BibliotecaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BibliotecaRoute,
} as any)
const AlunosIdRoute = AlunosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlunosRoute,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/anamnese': typeof AnamneseRoute
  '/arquivos': typeof ArquivosRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/avisos': typeof AvisosRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/config': typeof ConfigRoute
  '/dieta': typeof DietaRoute
  '/elite': typeof EliteRoute
  '/evolucao': typeof EvolucaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRouteWithChildren
  '/loja-pro': typeof LojaProRouteWithChildren
  '/owner': typeof OwnerRoute
  '/personais': typeof PersonaisRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRoute
  '/suporte': typeof SuporteRoute
  '/trainer': typeof TrainerRoute
  '/treinos': typeof TreinosRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/loja-pro/config': typeof LojaProConfigRoute
  '/loja/$id': typeof LojaIdRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/anamnese': typeof AnamneseRoute
  '/arquivos': typeof ArquivosRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/avisos': typeof AvisosRoute
  '/config': typeof ConfigRoute
  '/dieta': typeof DietaRoute
  '/elite': typeof EliteRoute
  '/evolucao': typeof EvolucaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRouteWithChildren
  '/loja-pro': typeof LojaProRouteWithChildren
  '/owner': typeof OwnerRoute
  '/personais': typeof PersonaisRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRoute
  '/suporte': typeof SuporteRoute
  '/trainer': typeof TrainerRoute
  '/treinos': typeof TreinosRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/loja-pro/config': typeof LojaProConfigRoute
  '/loja/$id': typeof LojaIdRoute
  '/biblioteca': typeof BibliotecaIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/anamnese': typeof AnamneseRoute
  '/arquivos': typeof ArquivosRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/avisos': typeof AvisosRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/config': typeof ConfigRoute
  '/dieta': typeof DietaRoute
  '/elite': typeof EliteRoute
  '/evolucao': typeof EvolucaoRoute
  '/financeiro': typeof FinanceiroRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRouteWithChildren
  '/loja-pro': typeof LojaProRouteWithChildren
  '/owner': typeof OwnerRoute
  '/personais': typeof PersonaisRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof StudentRoute
  '/suporte': typeof SuporteRoute
  '/trainer': typeof TrainerRoute
  '/treinos': typeof TreinosRoute
  '/alunos/$id': typeof AlunosIdRoute
  '/biblioteca/$id': typeof BibliotecaIdRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/loja-pro/config': typeof LojaProConfigRoute
  '/loja/$id': typeof LojaIdRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/alunos'
    | '/anamnese'
    | '/arquivos'
    | '/auth'
    | '/avaliacoes'
    | '/avisos'
    | '/biblioteca'
    | '/config'
    | '/dieta'
    | '/elite'
    | '/evolucao'
    | '/financeiro'
    | '/historico'
    | '/login'
    | '/loja'
    | '/loja-pro'
    | '/owner'
    | '/personais'
    | '/planos'
    | '/produtos'
    | '/reset-password'
    | '/student'
    | '/suporte'
    | '/trainer'
    | '/treinos'
    | '/alunos/$id'
    | '/biblioteca/$id'
    | '/checkout/$planId'
    | '/loja-pro/config'
    | '/loja/$id'
    | '/biblioteca/'
    | '/api/public/mp-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/alunos'
    | '/anamnese'
    | '/arquivos'
    | '/auth'
    | '/avaliacoes'
    | '/avisos'
    | '/config'
    | '/dieta'
    | '/elite'
    | '/evolucao'
    | '/financeiro'
    | '/historico'
    | '/login'
    | '/loja'
    | '/loja-pro'
    | '/owner'
    | '/personais'
    | '/planos'
    | '/produtos'
    | '/reset-password'
    | '/student'
    | '/suporte'
    | '/trainer'
    | '/treinos'
    | '/alunos/$id'
    | '/biblioteca/$id'
    | '/checkout/$planId'
    | '/loja-pro/config'
    | '/loja/$id'
    | '/biblioteca'
    | '/api/public/mp-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/alunos'
    | '/anamnese'
    | '/arquivos'
    | '/auth'
    | '/avaliacoes'
    | '/avisos'
    | '/biblioteca'
    | '/config'
    | '/dieta'
    | '/elite'
    | '/evolucao'
    | '/financeiro'
    | '/historico'
    | '/login'
    | '/loja'
    | '/loja-pro'
    | '/owner'
    | '/personais'
    | '/planos'
    | '/produtos'
    | '/reset-password'
    | '/student'
    | '/suporte'
    | '/trainer'
    | '/treinos'
    | '/alunos/$id'
    | '/biblioteca/$id'
    | '/checkout/$planId'
    | '/loja-pro/config'
    | '/loja/$id'
    | '/biblioteca/'
    | '/api/public/mp-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  AlunosRoute: typeof AlunosRouteWithChildren
  AnamneseRoute: typeof AnamneseRoute
  ArquivosRoute: typeof ArquivosRoute
  AuthRoute: typeof AuthRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  AvisosRoute: typeof AvisosRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  ConfigRoute: typeof ConfigRoute
  DietaRoute: typeof DietaRoute
  EliteRoute: typeof EliteRoute
  EvolucaoRoute: typeof EvolucaoRoute
  FinanceiroRoute: typeof FinanceiroRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRouteWithChildren
  LojaProRoute: typeof LojaProRouteWithChildren
  OwnerRoute: typeof OwnerRoute
  PersonaisRoute: typeof PersonaisRoute
  PlanosRoute: typeof PlanosRoute
  ProdutosRoute: typeof ProdutosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentRoute: typeof StudentRoute
  SuporteRoute: typeof SuporteRoute
  TrainerRoute: typeof TrainerRoute
  TreinosRoute: typeof TreinosRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinos': {
      id: '/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof TreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personais': {
      id: '/personais'
      path: '/personais'
      fullPath: '/personais'
      preLoaderRoute: typeof PersonaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja-pro': {
      id: '/loja-pro'
      path: '/loja-pro'
      fullPath: '/loja-pro'
      preLoaderRoute: typeof LojaProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite': {
      id: '/elite'
      path: '/elite'
      fullPath: '/elite'
      preLoaderRoute: typeof EliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivos': {
      id: '/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof ArquivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamnese': {
      id: '/anamnese'
      path: '/anamnese'
      fullPath: '/anamnese'
      preLoaderRoute: typeof AnamneseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/loja/$id': {
      id: '/loja/$id'
      path: '/$id'
      fullPath: '/loja/$id'
      preLoaderRoute: typeof LojaIdRouteImport
      parentRoute: typeof LojaRoute
    }
    '/loja-pro/config': {
      id: '/loja-pro/config'
      path: '/config'
      fullPath: '/loja-pro/config'
      preLoaderRoute: typeof LojaProConfigRouteImport
      parentRoute: typeof LojaProRoute
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/$id': {
      id: '/biblioteca/$id'
      path: '/$id'
      fullPath: '/biblioteca/$id'
      preLoaderRoute: typeof BibliotecaIdRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/alunos/$id': {
      id: '/alunos/$id'
      path: '/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AlunosIdRouteImport
      parentRoute: typeof AlunosRoute
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AlunosRouteChildren {
  AlunosIdRoute: typeof AlunosIdRoute
}

const AlunosRouteChildren: AlunosRouteChildren = {
  AlunosIdRoute: AlunosIdRoute,
}

const AlunosRouteWithChildren =
  AlunosRoute._addFileChildren(AlunosRouteChildren)

interface BibliotecaRouteChildren {
  BibliotecaIdRoute: typeof BibliotecaIdRoute
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaIdRoute: BibliotecaIdRoute,
  BibliotecaIndexRoute: BibliotecaIndexRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

interface LojaRouteChildren {
  LojaIdRoute: typeof LojaIdRoute
}

const LojaRouteChildren: LojaRouteChildren = {
  LojaIdRoute: LojaIdRoute,
}

const LojaRouteWithChildren = LojaRoute._addFileChildren(LojaRouteChildren)

interface LojaProRouteChildren {
  LojaProConfigRoute: typeof LojaProConfigRoute
}

const LojaProRouteChildren: LojaProRouteChildren = {
  LojaProConfigRoute: LojaProConfigRoute,
}

const LojaProRouteWithChildren =
  LojaProRoute._addFileChildren(LojaProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  AlunosRoute: AlunosRouteWithChildren,
  AnamneseRoute: AnamneseRoute,
  ArquivosRoute: ArquivosRoute,
  AuthRoute: AuthRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  AvisosRoute: AvisosRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  ConfigRoute: ConfigRoute,
  DietaRoute: DietaRoute,
  EliteRoute: EliteRoute,
  EvolucaoRoute: EvolucaoRoute,
  FinanceiroRoute: FinanceiroRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRouteWithChildren,
  LojaProRoute: LojaProRouteWithChildren,
  OwnerRoute: OwnerRoute,
  PersonaisRoute: PersonaisRoute,
  PlanosRoute: PlanosRoute,
  ProdutosRoute: ProdutosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentRoute: StudentRoute,
  SuporteRoute: SuporteRoute,
  TrainerRoute: TrainerRoute,
  TreinosRoute: TreinosRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
